# Catppuccin Mocha — Mauve
theme:
  activeBorderColor:
    - "#cba6f7"
    - bold
  inactiveBorderColor:
    - "#a6adc8"
  searchingActiveBorderColor:
    - "#f9e2af"
    - bold
  optionsTextColor:
    - "#89b4fa"
  selectedLineBgColor:
    - "#313244"
  inactiveViewSelectedLineBgColor:
    - "#1e1e2e"
  cherryPickedCommitBgColor:
    - "#45475a"
  cherryPickedCommitFgColor:
    - "#cba6f7"
  markedBaseCommitBgColor:
    - "#f9e2af"
  markedBaseCommitFgColor:
    - "#1e1e2e"
  unstagedChangesColor:
    - "#f38ba8"
  defaultFgColor:
    - "#cdd6f4"

authorColors:
  "*": "#b4befe"

# Git
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  commit:
    signOff: false
  merging:
    manualCommit: false
  log:
    order: topo-order
    showGraph: whenMaximised
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"

# UI
gui:
  nerdFontsVersion: "3"
  border: rounded
  showRandomTip: false
  showCommandLog: false
  showBottomLine: true
  expandFocusedSidePanel: false
  mainPanelSplitMode: flexible
  language: "auto"
  mouseEvents: true
  scrollHeight: 5
  scrollPastBottom: true
  sidePanelWidth: 0.25
  commitLength:
    show: true
  skipDiscardChangeWarning: false
  skipStashWarning: false

# Keybindings
keybinding:
  universal:
    quit: "q"
    quit-alt1: "<c-c>"
    togglePanel: "<tab>"
    prevItem: "<up>"
    nextItem: "<down>"
    prevBlock: "<left>"
    nextBlock: "<right>"
    optionMenu: "?"
    select: "<space>"
    goInto: "<enter>"
    remove: "d"
    new: "n"
    edit: "e"
    openFile: "o"
    scrollUpMain: "<pgup>"
    scrollDownMain: "<pgdn>"
    scrollUpMain-alt1: "K"
    scrollDownMain-alt1: "J"
    copyToClipboard: "<c-o>"
    submitEditorInfo: "<enter>"
    extrasMenu: "@"
  commits:
    squashDown: "s"
    rewordCommit: "r"
    renameCommit: "R"
    viewResetOptions: "g"
    markAsBaseCommit: "B"
    cherryPickCopy: "C"
    pasteCommits: "V"
    createFixupCommit: "f"
    squashAboveCommits: "F"

# Misc
notARepository: "prompt"
promptToReturnFromSubprocess: false
update:
  method: never
